# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: "Chicago" }, { name: "Copenhagen" }])
#   Mayor.create(name: "Emanuel", city: cities.first)
players = [
    ["Egan Berne","Sophomore","Chicago, Ill.","rowing_playerpic1.jpg",10],
    ["Erika Clary","Junior","Chapel Hill, N.C.","rowing_playerpic2.jpg",10],
    ["Lauren Colberg","Junior","Cary, N.C.","rowing_playerpic3.jpg",10],
    ["Sarah Eastley","Senior","Cary, N.C.","rowing_playerpic4.jpg",10],
    ["Steph Henrich","Senior","Wyndmoor, Pa.","rowing_playerpic5.jpg",10],
    ["Heather Gearhart","Junior","Chula Vista, Calif. ","volleyball_playerpic1.jpg",1],
    ["Leigh Andrews","Junior","Ft. Lauderdale, Fla. ","volleyball_playerpic2.jpg",1],
    ["Beth Nordhorn","Freshman","Winter Park, Fla.","volleyball_playerpic3.jpg",1],
    ["Paige Neuenfeldt","Junior","Birmingham, Mich. ","volleyball_playerpic4.jpg",1],
    ["Victoria McPherson","Junior","Ft. Lauderdale, Fla. ","volleyball_playerpic5.jpg",1],
    ["Hayley Carter","Sophomore","Hilton Head, SC ","tennis_female_playerpic1.jpg",2],
    ["Ashley Dai","Junior","Temple City, Calif. ","tennis_female_playerpic2.jpg",2],
    ["Whitney Kay","Junior","Alpharetta, Ga. ","tennis_female_playerpic3.jpg",2],
    ["Jamie Loeb","Sophomore","Ossining, NY ","tennis_female_playerpic4.jpg",2],
    ["Kate Vialle","Junior","Leawood, Kan. ","tennis_female_playerpic5.jpg",2],
    ["Margaret Brown","Sophomore","Waxhaw, N.C.","gymnastics_playerpic1.jpg",3],
    ["Lexi Cappalli","Junior","Kildeer, Ill. ","gymnastics_playerpic2.jpg",3],
    ["Josselyn Mackey","Junior","Lee's Summit, Mo. ","gymnastics_playerpic3.jpg",3],
    ["Haley Watts","Senior","Charlotte, N.C. ","gymnastics_playerpic4.jpg",3],
    ["Janell Sargent","Senior","Greenville, N.C. ","gymnastics_playerpic5.jpg",3],
    ["Leslie Cloots","Junior","Antwerp, Belgium ","golf_female_playerpic1.jpg",4],
    ["Lexi Harkins","Senior","Crystal Lake, Ill. ","golf_female_playerpic2.jpg",4],
    ["Rachel Jones","Sophomore","Asheboro, N.C. ","golf_female_playerpic3.jpg",4],
    ["Elizabeth Mallet","Sophomore","Sutton Coldfield, England ","golf_female_playerpic4.jpg",4],
    ["Maia Schechter","Junior","Takoma Park, Md. ","golf_female_playerpic5.jpg",4],
    ["Collions Allison","Junior","Sammamish, Wash. ","fencing_playerpic1.jpg",5],
    ["Sam Austin","Junior","Dix Hills, N.Y. ","fencing_playerpic2.jpg",5],
    ["Ezra Baeli-Wang","Sophomore","Hillsborough, N.J. ","fencing_playerpic3.jpg",5],
    ["Alexander Burte","Junior","Cincinnati, Ohio ","fencing_playerpic4.jpg",5],
    ["Deven Desai","Freshman","Westborough, Mass. ","fencing_playerpic5.jpg",5],
    ["Jessica Pereira","Freshman","Palmerton, Pa. ","fieldhockey_playerpic1.jpg",6],
    ["Loren Shealy","Senior","Charlotte, N.C. ","fieldhockey_playerpic2.jpg",6],
    ["Kristy Bernatchez","Sophomore","Belgrade, Maine ","fieldhockey_playerpic3.jpg",6],
    ["Samantha Travers","Senior"," Harare, Zimbabwe","fieldhockey_playerpic4.jpg",6],
    ["Charlotte Craddock","Senior","Wolverhampton, England ","fieldhockey_playerpic5.jpg",6],
    ["Davis Bateman","Sophomore","Charlotte, N.C.","golf_male_playerpic1.jpg",7],
    ["Keagan Cummings","Junior","Dublin, Ireland ","golf_male_playerpic2.jpg",7],
    ["Brandon Dalinka","Senior","Newtown, Pa. ","golf_male_playerpic3.jpg",7],
    ["Henry Do","Junior","Canton, MI ","golf_male_playerpic4.jpg",7],
    ["Zachary Martin","Sophomore","Pinehurst, N.C. ","golf_male_playerpic5.jpg",7],
    ["Brett Clark","Junior","Naples, Fla. ","tennis_male_playerpic1.jpg",8],
    ["Connor Daly","Junior","Thousand Oaks, Calif. ","tennis_male_playerpic2.jpg",8],
    ["Stuart DePaolo","Junior","Asheville, N.C. ","tennis_male_playerpic3.jpg",8],
    ["Oystein Steiro","Junior","Snaroya, Norway ","tennis_male_playerpic4.jpg",8],
    ["Ronnie Schneider","Sophomore","Bloomington, Ind. ","tennis_male_playerpic5.jpg",8],
    ["Frank Abbondanza","Senior"," Mount Sinai, N.Y.","wrestling_playerpic1.jpg",9],
    ["Christian Barber","Junior","Westfield, N.J. ","wrestling_playerpic2.jpg",9],
    ["Houston Clements","Junior","Chattanooga, Tenn.","wrestling_playerpic3.jpg",9],
    ["Evan Henderson","Senior","New Florence, Pa. ","wrestling_playerpic4.jpg",9],
    ["Jacob Crawford","Junior","Tunis, TN","wrestling_playerpic5.jpg",9]
]

teams = [
    ["Volleyball","Women's","Joe Sagula","Eve Rackham","volleyball_teampic.jpg"],
    ["Tennis","Women's","Brian Kalbas","Courtney Nagle","tennis_female_teampic.jpg"],
    ["Gymnastics","Women's","Derek Galvin","Amy Smith","gymnastics_female_teampic.jpg"],
    ["Golf","Women's","Jay Mann","Leah Buchmann","golf_female_teampic.jpg"],
    ["Fencing","Men's","Ron Miller","Josh Webb","fencing_teampic.jpg"],
    ["Field Hockey","Women's","Karen Shelton","Grant Fulton","fieldhockey_female_teampic.jpg"],
    ["Golf","Men's","Andrew Sapp","Andrew DiBitetto","golf_male_teampic.jpg"],
    ["Tennis","Men's","Sam Paul","Tripp Phillips","tennis_male_teampic.jpg"],
    ["Wrestling","Men's","C.D. Mock","Coleman Scott","wrestling_male_teampic.jpg"],
    ["Rowing","Women's","Sarah Haney","Anthony Brock, Emily Caflisch","rowing_female_teampic.jpg"]
]
bios = [
    ["Graduate of Loyola Academy ... Rowerd for Loyola Academy Rowing Association for three years, serving as team captain her senior year ... Her JV8 won the Midwest Championship in 2011 ... Played basketball all four years and was team captain as a senior ... Played soccer as a freshman ... Picked up rowing as a sophomore at the suggestion of her basketball coach","In her first season on the varsity squad","Born in Chicago, Ill. ... Daughter of Linda and Jason Berne ... Has a younger brother and a younger sister ... Favorite pastimes are reading, painting, biking and driving around blasting music ... Favorite sport other than rowing is basketball ... Loves Batman ... Fun fact is that she lived in Dubai, UAE, when she was younger ... Athlete she most admires is Dennis Rodman ... After graduation, hopes eventually to become a criminal profiler in the violent crimes section of the FBI, but first she wants to return to Chicago to coach at her high school while working on a master's degree ... Dream job is to be a film director like Quentin Tarantino ... Little-known talent is making owl calls",1],
    ["At East Chapel Hill High, lettered three years in field hockey and three years in track and field. Working toward a double major in exercise and sport science and psychology","In her first year on the varsity after coxing for the novice squad last year","Born July 25, 1994, in Durham, N.C. ... Daughter of Monica and Bryan Clary ... Has two younger brothers and a younger sister ... Favorite pastimes are working out and writing ... Favorite sport other than rowing is field hockey ... Favorite book is 'The Book Thief'  ... Pet peeve is people talking on the silent floors of the library ... After graduation, plans to go on to graduate school and become a pediatric physical therapist ... Dream job is to be a poet ... Little-known talent is making a belt out of five gum wrappers",2],
    ["At Green Hope High School, earned 12 letters in cross country and indoor/outdoor track and field ... Part of three cross country state championship teams ... Also won state championships in the 4x800 relay and the 1600 ... Two-time team MVP. Majoring in biology ... Works in a fluid dynamics lab","In her first year on the varsity squad ... Rowed as part of the novice squad in 2012-13","Born in Royal Oak, Mich. ... Daughter of Mary and Keith Colberg ... Has two brothers and a sister ... Favorite pastime is going to the beach ... Favorite sport other than rowing is running ... Biggest pet peeve is arrogance ... Athlete she admires most is runner Alan Webb ... After graduation, plans to continue her education and become a physician assistant ... Dream job is to work for Doctors without Borders ... Little-known talent is crafting ",3],
    ["At Holly Springs High School, lettered in swimming an served as manager of the tennis team. Majoring in English with a minor in creative writing ... Serves as secretary and treasurer for her church representative group on campus (Latter-Day Saint Student Association)","In her second year as a varsity coxswain after spending her freshman year on the novice squad","Born in Woodbridge, Va., ... Daughter of Brian and Tiffany Eastley ... Has two younger brothers ... Favorite pastimes are reading, writing, watching TV, painting her nails, watching movies and hanging out with friends ... Favorite sport besides rowing is tennis ... Favorite food is seafood ... Favorite movie is The Little Mermaid ... Fun fact is that she has rappelled down an 80-foot cliff ... Dream job is to be a children's/young adult fiction author ... Little-known talent is painting designs on her nails",4],
    ["At Mount Saint Joseph Academy, rowed for four years ... Among her top finishes were fourth at Head of the Charles Regatta, first and third at Stotesbury, fourth and sixth at the Scholastic Rowing Association of America Regatta, first and second at Philadelphia Cities, second at Head of the Schuylkill, and first at Navy Day Regatta ... Also played one year of field hockey and two years of club lacrosse ... Picked up rowing in the spring of her freshman year after she started going to land practices in the winter to stay in shape for lacrosse","In her third year on the varsity squad ... Rowed in the second varsity eight as a freshman and the varsity four as a sophomore"," Born in Philadelphia, Pa...Daughter of Dave and Lisa Henrich ... Has a brother who played lacrosse at Villanova ... Favorite pastimes include hiking with her family and riding horses ...Favorite sport other than rowing is lacrosse ... Interesting fact is she as climbed 13 mountains ... The athlete she most admires is surfer Bethany Hamilton ... After graduation, hopes to work in marketing and advertising ... Dream job is to be a National Geographic photographer",5],
    ["Majoring in exercise and sport science - sport administration, and minoring in coaching education and recreation administration • member of the Richard A. Baddour Carolina Leadership Academy as a CREED mentor • Named to the ACC Honor Roll for the 2013-2014 academic year • Sister played softball at Oklahoma State University for four years • Born Dec. 2, 1994, in Chula Vista, Calif. • Heather Janneé Gearhart is the daughter of Dawn Gearhart and Sam Shuey.","Played 62 sets in 25 matches • Tallied 14 services aces and 57 digs • Posted career highs of eight digs vs. Maryland (10/25) and four aces vs. Virginia (10/18). ","Recorded more than 600 digs, and had 50 serving aces, 38 assists, two blocks and eight kills during her senior campaign • Named to the 2011 All-League Academic team • Named team co-captain as a senior • Named First Team All-Mesa League twice and played in the Mesa League All-Star game • Named to the CIF San Diego Section First Team and played in the SD County All-Star game • Named MVP and Most Valuable Libero of La Jolla Beach City Invitational • Third Team Defensive Dandy on PrepVolleyball.com • Member of the California Scholarship Federation.",6],
    ["The #97 recruit in the nation • Played volleyball three years at Westminster Academy and one at Cardinal Gibbons • Helped Cardinal Gibbons advance to the state semi-final game in 2011 • Also competed in track and field • Was the team captain and named MVP after helping her team to the 2010 Team Florida High Performance Championship • Helped team to state runner-up in Class 2A at Westminster Academy in 2010 • Named the Broward County Player of the Year in 2008, 2009 and 2010 • Received 2011-12 UnderArmour All-America honorable mention  honors •Also named the Miami Herald Player of the Year in 2008, 2009 and 2011 • Helped team to Beast of the Southeast Championship in 2011 and 2012 and was named the MVP in 2012 • 2010 Huntington Beach Volleyball 18u Championship Runner Up •  Named to academic honor roll • Named one of 35 finalists for PrepVolleyball.com's  2010 National High School Junior of the Year award.","Started 31 of 32 matches in 2013 • Named the Middle Tennessee State Blue Raider Bash Tournament MVP • Recorded six double-doubles and tallied 10+ digs in 15 matches • Had career highs of 15 kills vs. FSU (11/1) and 22 digs vs. Maryland (10/25) • Tied her career-high three aces vs. Cincinnati (9/7) • Ranked second on the team with 335 digs (2.99/set) and third in kills with 241 (2.15/) set • Also ranked third on the team with 26 aces.","Born Feb. 4, 1994, in Fort Lauderdale, Fla. • Hobbies include scuba diving and tennis •  Leigh Meredith Andrew is the daughter of Scott and Margie Andrew.",7],
    ["Ranked as the #72 overall recruit by PrepVolleyball.com • One of just 10 middle blockers named to PrepVolleyball.com's Top 50 Juniors List • Helped her team to Florida 8A High School State Championship in 2013 • Named to AVCA High School All-America first team as a senior • Led her Orlando Volleyball Academy (OVA) 17 Asics team to back-to-back USAV National appearances in 2013 and 2014  • Helped her OVA 15 Asics team win the Big South Qualifier in Atlanta • Named All-Metro twice • Helped her high school team to runner-up finish at state championships as a sophomore.",
     "Kills: 8 vs. VCU (9/13/14) Blocks: 5 vs. VCU (9/13/14)","Plans to major in biomedical engineering • National Honor Society member • Part of the International Baccalaureate Program • Volunteers with the Winter Park Day Nursery, SPCA and at the local library • Anna Elizabeth Nordhorn was born Nov. 6 in Winter Park, Fla., and is the daughter of Marinanne and Peter Nordhorn.",8],
    ["Received UnderArmour All-America Honorable Mention • Named to Academic All-America Third Team • Also played basketball for two years while at Seaholm High School • Named Legacy team captain four years • Recorded 525 kills, 59 blocks, 78 aces, 383 digs, 29 assists with a 6.0 kpg average over her senior year • Named Michigan Miss Volleyball and Michigan Gatorade Player of the Year finalist • National Honor Society member for two years • Received Phi Beta Kappa and President’s Education Awards • Named to Principal’s List all four years. ","Earned AVCA Honorable Mention All-America honors for the second time in her career •Named to the AVCA East Coast Division I All-Region team • Earned All-ACC Second Team honors and was named to the All-ACC Academic team • Led the ACC in conference hitting percentage with .401 • Ranked second on the team in total kills, with 236 (2.13/set) while hitting .389 • Notched 10+ kills in seven matches and had 5+ blocks in 14 • Posted season highs of 14 kills twice, vs. Florida State (11/1) and vs. Duke (11/29), and seven blocks three times, vs. Cincinnati (9/7), vs. Virginia Tech (11/15) and vs. Duke (11/29)• Received the Sharon D. German Memorial/Best Offensive Player team award. ","Enrolled in the Kenan-Flagler Business School, and is a spanish for professions minor • Named to the ACC Honor Roll for the 2013-2014 academic year • Born April 11, 1994, in Royal Oak, Mich. • Paige Elizabeth Neuenfeldt is the daughter of Janie and Joe Neuenfeldt.",9],
    ["The #56 recruit in the nation • Named team captain as a senior • Helped team finish runners-up in state tournament • Named to Senior Aces Top 50 List • Was a member of student government and was the school yearbook editor-in-chief.","Received an Honorable Mention for the AVCA East Coast Division I All-Region Team • Earned All-ACC Third Team recognition • Led the Tar Heels and ranked sixth in the ACC with 121 total blocks (1.21/set) • Recorded career highs of 14 kills vs. Virginia (11/16) and vs. Pittsburgh (10/27), and eight blocks vs. Virginia (11/16) • Named ACC Co-Player of the Week on Sept. 23 and ACC Player of the Week on Nov. 18 • Ranked fourth on the team with 222 total kills (2.22/set) and third in attack percentage at .286.","Majoring in communications • Born Feb. 5, 1994, in Newark, N.J. • Victoria Danielle McPherson is the daughter of Gwen and Wade McPherson. ",10],
    ["No. 2 overall player in the class considered a Blue Chip prospect by TennisRecruiting.net • Played at the Smith Stearns Tennis Academy • Won a record 14 South Carolina state championships • Also a nine-time Southern region champion • Won the South Carolina IF event two years straight • Has won four USTA National Championship Gold Balls - three in singles and one doubles - as well as four bronze balls.","Ranked No. 3 in the final ITA Tennis rankings in both singles and doubles alongside Jamie Loeb in first season at North Carolina •","Won 16 straight singles matches, before falling to eventual national champion Danielle Collins of Virginia in the quarterfinals of the NCAA Singles Championship in Athens, Ga. • Reached the quarterfinals of Main Draw Singles at the Riviera/ITA Women's All-American Championship • Advanced to the Main Draw Singles bracket at the USTA/ITA National Indoor Intercollegiate Championship • Won the black draw singles title at the season opening Duke Fab Four Invitational • Reached the singles final of the ITA Carolinas Regional, before falling in three sets to Duke's Beatrice Capra • Teamed with Loeb to win the doubles title at the ITA Carolinas Regional. ",11],

    ["No. 10 overall player in the class and considered a Blue Chip prospect by TennisRecruiting.net • Three-time UTSA Gold Ball winner • Won the Winter National Championships doubles title three straight years from 2007 to 2009 • Captured the Casablanca ITF G4 singles event in 2010 • Part of a team that won the 2011 16s Intersectionals, and she was undefeated in the event.","Finished the season ranked No. 97 in the final ITA Tennis singles rankings • Recorded a 17-10 singles record, including a 12-7 dual match record • Went 4-1 in ACC singles competition • Was ranked in the top-100 for most of the season • Finished the season by winning 11 of 13 singles matches • Took 13th-ranked Chanelle Van Nguyen to three sets in NCAA Championship final against UCLA • In doubles, owned a 13-5 record playing with Tessa Lyons • Their best win was 8-2 over 71st ranked Alabama in the quarterfinals of the NCAA Championship that clinched the doubles point over the Crimson Tide • Also went 5-0 playing with Jamie Loeb that saw the duo briefly ranked No. 76 in the ITA doubles rankings in early May • Dai/Loeb beat Duke's 30th ranked Goldfeld/Smith, 8-3, in the quarters of the ACC Championship. ","Finished with an overall singles record of 19-7, including an 11-3 mark in dual match play • Went 3-2 in ACC singles play • Was ranked as high as No. 65 in the country in singles and finished at No. 121 • Won 10-straight singles matches that spanned seven weeks of competition • Teamed with Whitney Kay to form a strong doubles combination that owned a 15-8 overall doubles record • The duo ranked No. 8 nationally in early January and finished the season No. 33 in the country • Dai and Kay won their first nine doubles matches of the season, including two victories over ranked opponents from Tennessee and Florida State at the Furman Fall Classic • Also joined Lauren McHale in doubles and the two notched a 3-0 record, including a win at Boston College and an 8-2 victory over Nebraska's Weinstein and Weinreich in the NCAA Round of 16 • Also went 7-3, including 5-2, with Zoe De Bruycker and 4-0 matched with Caroline Price in doubles.",12],
    ["No. 5 overall player in the class and considered a Blue Chip prospect by TennisRecruiting.net • One of the nation's top junior players for the last several years, has been ranked No. 1 in the Southern Section since the age of 14 and reached the No. 1 spot in the national rankings in 2010 • Winner of the Southern Closed Championship at the 12s, 14s and 18s • Has won 10 USTA National Championship Gold Balls and 8 USTA National Championship Silver Balls as well as a number of regional and national sportsmanship awards, including at the 2009 USTA National Championship Hard Courts and the 2010 USTA Spring Nationals.","Earned All-America status in doubles playing with partner Caroline Price • The duo earned an at-large bid to the NCAA Doubles Championship and reached the quarterfinals • Kay and Price finished the season ranked No. 9 according to the ITA • Kay/Price finished with a 25-8 overall doubles record, including 18-5 in dual matches and an 8-2 mark against the ACC • They were 9-3 at #1 and 9-2 at #2 doubles • The tandem won four doubles matches in the NCAA Team Championship over VCU, Texas A&M, Alabama and Stanford • Beat #3 Michigan (Bolender/Bektas) and #7 William & Mary (Belaya/Loomans) at Riviera ITA All-Americans to advance into semifinals of Main Draw Doubles • Posted a 13-15 singles record • Defeated Texas A&M's Stefania Hristov in straight sets in the NCAA Team Championship • Was ranked as high as #33 by the ITA in singles. "," Enjoyed an outstanding first season with Carolina by posting a 31-14 overall singles record, including a 19-5 mark in dual match play • Her 8-1 record in ACC competition led the team • Was ranked as high as No. 19 nationally in singles and finished the season at No. 44 in the country • Won her first three collegiate matches at the Duke Fab Four, including a straight-set victory over No. 17 Cristinia Stancu of Texas A&M • Earned 12-straight singles wins that spanned two months of the spring season • That included three wins in leading Carolina to the National Indoor title in February • She had victories over No. 19 Zoe Scandalis of USC, 6-2, 5-7, 6-3, No. 40 Ester Goldfield of Duke in straight-sets and No. 96 Pamela Montez of UCLA, 6-2, 4-6, 7-6 (5) • Teamed with Ashley Dai to form a strong doubles combination that owned a 15-8 overall doubles record • The duo ranked No. 8 nationally in early January and finished the season No. 33 in the country • Dai and Kay won their first nine doubles matches of the season, including two victories over ranked opponents from Tennessee and Florida State at the Furman Fall Classic • Kay later joined forces with Caroline Price and went 13-4 in doubles, including 10-3 in dual matches • The duo went 5-2 in the ACC and also took down No. 8 Northwestern, 9-8 (6) in Evanston, Ill. • Price and Kay finished the season ranked No. 37 in the country.",13],
    ["Won the inaugural American Collegiate Invitational at the US Open • Defeated Virginia's Julia Elbaba in straight sets to earn the title • Loeb also beat UCLA's Jennifer Brady and defending NCAA singles champion Danielle Collins of Virginia in straight sets in the 8-player draw at the USTA Billie Jean King National Tennis Center. ","53-4 overall singles record, 31-2 in dual matches, 14-0 in ACC • Nation's top-ranked women's tennis player • ITA All-America in both singles and doubles • ITA National Player and Rookie of the Year • ACC Player of the Year • First Team All-ACC • One of four nominees for the Honda Sports Award for women's tennis • First Carolina player to be ranked No. 1 in singles, held top ranking from Feb. 11 until final ranking in June • Teamed with Hayley Carter for the No. 3 doubles tandem in the country with a final record of 34-6 • Won ACC Player of the Week honors three times • Was the top seed in NCAA Singles bracket and advanced to the quarterfinals • Loeb and Carter were the No. 3 seed in the NCAA Doubles bracket and reached the quarterfinals • Became the first freshman in almost 30 years to win both the Riviera/ITA Women's All-American Championship and the USTA/ITA National Indoor Intercollegiate Championship in the same season • Helped guide the Tar Heels to a runner-up finish at the 2014 NCAA Team Championship, the first national championship match appearance in program history • North Carolina finished the season ranked No. 3 nationally • 36 of her 53 singles victories came over ranked opponents, including 10 wins over top-10 ranked players."," No. 1 overall player in the class considered a Blue Chip prospect by TennisRecruiting.net • Competed in the 2013 U.S. Open Main Draw Qualifier, defeating Veronica Cepede Roug, 6-1, 6-3, who was ranked 193rd in the world at the time • Was a quarterfinalist at the 2013 Wimbledon Juniors • Won the doubles and finished runner-up in singles at the 2013 USTA International Spring Championship in Carson, Calif. • Won both the singles and doubles 18s titles at the 2012 USTA National Winter Championship • Has already won a pair of pro tournaments, the $10,000 Futures events in Buffalo and Amelia Island • Swept singles and doubles titles at the ITF Grade 4 event in Delray Beach, Fla., in May 2012.",14],
    ["No. 17 overall player in the class and considered a blue chip prospect by TennisRecruiting.net • USTA National Championship gold ball winner and USTA National Championship silver ball winner • USTA National Open singles and doubles winner • Agassi No Quit award winner • USTA National Open Sportsmanship Award winner • Also won the Missouri Valley Heart of America Player of the Year Award and completed her Missouri Valley Section career with the No. 1 ranking • Her father, mother and grandfather played college tennis.","Finished the season with a 20-7 record in singles play, including 19-6 in dual matches and 12-2 in the ACC • Defeated No. 75 Catherine Harrison of UCLA, 6-4, 6-4, at #5 singles in the NCAA Championship match • Also beat Alabama's Emily Zabor in the NCAA quarterfinals, 6-1, 6-4 • Won six-straight matches against ACC opponents • Teamed with Laura Slater to post a 13-8 doubles mark, including a 5-4 dual match record • Slater/Vialle advanced to the finals of the ITA Carolinas Regional, falling to teammates Hayley Carter and Jamie Loeb, 8-2 • Played with Ashley Dai in the ACC Championship and won 8-4 over Florida State. ","Joined the program in January and finished with an impressive 9-2 overall singles record • She was 8-1 in dual matches, including 3-1 against the ACC • She won five-straight singles matches and eight of her final nine to end the year • The final two victories came in straight sets over Melissa Bolivar of Miami in the ACC Semifinals and against Nebraska's Izabella Zgierska in the NCAA Round of 16 • Finished with a 5-3 overall doubles record • Was 3-1 combined with Gina Suarez-Malaguti.",15],
    ["Trained at Southeastern Gymnastics in Weddington, N.C., under the direction of Ludmilla Shobe "," Placed third on floor, sixth on beam and sixth in the all-around at the Level 10 state championships • Missed most of her 2012 season with elbow surgery • Was a Level 10 performer at the states, finishing third on uneven bars and fifth on balance beam","Attended Cuthbertson High School where she was a member of the National Honor Society • Member of the Fellowship of Christian Athletes • Volunteer at several community events, including Fixing it Up For Christ, Elevation Church, Girls on the Run and the Henderson County Special Olympics.",16],

    ["Attended Adlai E. Stevenson High School in Lincolnshire, Ill...Trained under the guidance of head coach Todd Gardiner at Illinois Gymnastics Institute...Junior Olympic Nationals Qualifier 2010...Placed second on vault and fifth in the all-around at the V Region Championships in 2010.","Enters the 2014 season looking to improve on a solid rookie campaign • Has the ability to be an all-around after focusing primarily on vault, bars and floor a year ago.","Scored a season-high 9.825 on vault to finish fifth against George Washington and William & Mary • Set a season-high on floor in three different meets with a score of 9.850 at the EAGL championships, vs. Penn and at Pitt • Posted a season-best 9.850 on uneven bars at Oklahoma • Won the floor competition at home vs. Penn and was second on floor at the EAGL to capture All-conference tournament honors.",17],
    ["Attended Lee's Summit North High School in Lee's Summit, Mo. • Trained at Xtreme Gymnastics under the guidance of Alisha Robinson ","Selected to the EAGL All-Academic team • Competed in every meet on balance beam • Also was a regular in the uneven bars and vault lineup • Competed on floor in just two meets • Had her season-high score on vault with a 9.600 at home against George Washington and on the road at Maryland • Posted a season-best 9.800 on the balance beam to finish second in the home meet vs. Maryland ","Four-time Junior Olympic National Qualifier • Placed second at the 2012 Junior Olympic national championships • Placed sixth on balance beam at the 2011 National Championships • Placed 10th on balance beam and 12th in the all-around at 2010 National Championships.",18],
    ["Has been one of the top gymnasts in North Carolina for the past several years • Trained under the direction of Ludmilla Shobe at Southeastern Gymnastics • Has been involved in gymnastics since the age of 3 • Was a 2008, 2009, and 2010 Level 10 Junior Olympic National Qualifier • Placed 10th in the All-Around in 2008 & 2009, and she finished fifth in the All-Around in 2010 at the USA Gymnastics Junior Olympic National Championships. ",
     "One of the most consistent performers on the team • Had a strong sophomore season and has a bright future.","Battled teammate Elizabeth Durkac for top all-around scores every week • Took home EAGL Gymnast of the Week honors after posting a 39.225 in the all-around competition vs. Maryland to finish first • Also scored more than a 39.0 in the all-around at NC State, at Oklahoma, vs. Penn and at the EAGL championships • Scored a 39.0 at both the EAGL championships and the NCAA regionals to place ninth in both meets • Scored season-highs on vault (9.850) and floor (9.850) against the Terps • Finished first on the floor in that meet • Also had a 9.850 on floor at NC State • Recorded season-highs on bars with a 9.850 at Oklahoma at vs. Penn • Finished in second place on bars vs. the Quakers • Had a season-high 9.775 on balance beam in two different meets.",19],
    ["Born Janell Elizabeth Sargent on January 1, 1993 in Minneapolis • Daughter of Andy and Pam Sargent • Was home schooled by her parents • Volunteered twice a month at Reimage Church in the children's curriculum • Played the violin as a child • Her father, Andy, is a chemistry professor at East Carolina University. ","Competed in seven meets as part of the balance beam lineup • Posted a season-best 9.750 in a road meet at Penn State and at the NCAA Regional in Raleigh • Also had a 9.725 on three occasions - vs. Temple on Feb. 17, George Washington on Feb. 24 and at the EAGL Championship on March 24 • Earned EAGL All-Academic honors. ","Was one of the top Junior Olympic gymnasts in North Carolina for many years • Attended Roses' Gymnastics in Greenville, N.C., where she trained under the guidance of Darlene Rose, Colin Womack and Shelley Harris • Two-time USA Gymnastics Junior Olympic Level 10 National qualifier • Roses' training program has produced several outstanding student athletes that pursued their college experiences at Carolina.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Named a Scholastic All-America by the National Association of Collegiate Gymnastics Coaches • Selected to the EAGL All-Academic team • Competed in all 12 meets as a balance beam specialist • Posted a season-high 9.900 to finish second at NC State and Pittsburgh • Posted a score of 9.700 or higher in nine of 12 meets on beam • Tied for second in the beam competition in the meet at George Washington and at Pitt.",20],
    ["Majoring in Business Administration ... selected 2014 WGCA All-America Scholar ... named to 2014 ACC Honor Roll.     ","Competed in nine out of 10 tournaments, including one as an individual ... played in all six of the spring tournaments ... top performance was a tie for 28th place at the SMU/Dallas Athletic Club Invitational ... tied for 35th at the ACC Championships, tied for 44th at the Northrop Grumman Regional Challenge, tied for 49th at the Darius Rucker Intercollegiate, tied for 66th at the NCAA Central Regional and tied for 76th at the Bryan National Collegiate ... top performance in the fall was a tie for 41st at the Mason Rudolph Championship ... tied for 61st at the Dale McNamara NCAA Fall Preview and tied for 68th at the Ruth's Chris Tar Heel Invitational while competing as an individual ... 76.65 stroke average ... carded one even par score.","Runner-up at 2014 British Ladies Amateur Championship ... played in 2014 SRIXON XX0 Ladies Open, part of China's LPGA Tour ... 2013 European Ladies' Team Champion for Belgium ... member of 2012 Belgium Ladies National Team and played in the 2012 World Amateur in Turkey ... 2012 Grand Prix AFG winnder and 2012 King's Prize runner-up ... tied for runner-up honors at 2012 Annika Invitational Europe and semifinalist at 2012 Belgium National Match Play Championship ... runner-up in stroke play qualifying for the 2012 British Girls Amateur Championship ... placed fifth at 2012 Belgium Ladies International Amateur and ninth at 2012 German International Ladies Amateur ... played on three-person team that finished 12th out of 53 national teams at 2012 World Amateur Team Championships ... participated in 2011 and 2012 European Girls' Team Championship for Belgium and ranked first in 2012 Belgium Girls Rankings to then move on to play in the Junior Orange Bowl Championship. ",21],

    ["Parents are Redmond and Alison Harkins.","Champion of 2014 Illinois Women's Amateur ... advance to championship flight of 2014 Women's Western Amateur ... 2012 Rolex All-America ... 2012 AJGA Lockton Kansas City Junior Champion ... medalist qualifier at 2013 U.S. Women's Amateur, advancing to the round of 16 ... two-time qualifier for U.S. Junior Girls Amateur.","Three-time golf letterwinner at Crystal Lake Central, 2010, 2011, 2013 ... three-time All-State (2010, 2011, 2013) ... three-time All-Conference (2010, 2011, 2013) ... finished third at 2011 State Championship, fourth at 2010 State Championship and 10th at 2013 State Championship ... team co-captain in 2013 ... selected to the honor roll all four years ...  two-time HP Scholastic Junior All-America in 2012 and 2013.",22],
    ["Parents are Jenny and Tommy Jones.","Champion of 2012 CJGT (Carolina Junior Golf Tour) Tour Championship … member of 2012 CGA Junior Girls All-State team … runner-up at 2013 Myrtle Beach Shootout … third place at TGF UNC Tar Heel … and two-time champion of Emma Duley Memorial Tournament at Old North State Club.","Four-time golf letterwinner at Southwestern Randolph … also lettered in basketball two years (freshman and sophomore years) … medalist of 2012 and 2013 Mid-Piedmont 3A Golf Conference … placed second in 2012 NCHSAA 3A Central Regional … placed fourth in the 2011 and 2012 3A NCHSAA State Championship … voted team MVP in 2010 and 2011 … excelled academically.",23],
    ["Parents are Neil and Beverley Mallett"," Competed in all 10 tournaments ... carded four top-10 finishes, all in the spring ... carded five top-20 finishes ... won the SMU/Dallas Athletic Club Invitational, her first collegiate win, with a 3-under-par 141 total to post a 5-stroke win ... placed seventh at the Darius Rucker Intercollegiate, eighth at the Bryan National Collegiate and tied for ninth at the ACC Championships ... her other top 20 finish was the first tournament of the fall where she tied for 17th place at the Dale McNamara NCAA Fall Preview ... also in the fall she tied for 27th at The Landfall Tradition, tied for 29th at the Mason Rudolph Championship and tied for 38th at the Ruth's Chris Tar Heel Invitational ... also tied for 38th at the Northrop Grumman Regional Challenge in the spring and tied for 73rd at the NCAA Central Regional ... led the team with a 74.00 stroke average ... carded three under-par rounds, two in the 60s, and one even par round."," Four-year golf letterwinner at Sutton Coldfield School ... 2011 silver medalist at European Girls Team Championship ... 2011 Nottinghamshire Girls Open Champion and 2011 Warwickshire School Girls Champion ... 2011 Birmingham Sports Personality of the Year ... 2010 English Girls Champion ... 2009 English U15 Girls Champion ... 2009 British Girls Open runner-up ... 2009 Warwickshire U15 Champion ... 2008 Warwickshire School Girls Champion ... 2008 Midland Schools Girls Champion ... third place at 2008 English U15 Championship ... 2007 Warwickshire School Girls Champion ... 2007 English School Girls Champion ... 2007 English U13 Championships runner-up ... 2006 English U13 Championships runner-up ... 2006 Warwickshire U15 Champion.",24],
    ["Parents are Maria Simonsson and Mark Schechter ... also a Swedish citizen.","Played in six of Carolina's four tournaments, including one as an individual ... top performance was a tie for 22nd place at the ACC Championships ... tied for 32nd at the Mason Rudolph Championship in the fall, competing as an individual ... also in the fall tied for 76th at the Ruth's Chris Tar Heel Invitational and tied for 88th at The Landfall Tradition ... in the spring, aside from her ACC performance she tied for 87th at the NCAA Central Regional and placed 89th at the Bryan National Collegiate ... 78.67 scoring average ... carded one under-par round.","Majoring in Exercise and Sport Science and American Studies ... selected 2014 WGCA All-America Scholar ...  named to the 2012, 2013 and 2014 ACC Honor Roll ... graduate of the Carolina Leadership Academy's Rising Stars program and now a CREED mentor.",25],
    ["Born in Dallas, Texas ... Son of Brian and Jill Allison ... Has one sister ... Favorite pastimes are playing pick-up basketball and Ultimate Frisbee, watching football and basketball, and playing FIFA ... Favorite sport other than fencing is basketball ... Athlete he most admires is Tim Tebow","In his second year on the squad. Graduate of Eastlake High in Sammamish, Wash. ... Fenced throughout high school after picking up the sport when he was in junior high","Enrolled in the General College and has not yet declared a major ",26],

    ["Attended Commack High School ... Fenced sabre for five years, serving as team captain ... All-Long Island in his junior and senior years ... Finished 30-0 as a senior ... Also played four years of soccer, earning all-conference honors as a junior ... Lettered one year in track "," Qualified for the 2013 NCAA Championships and finished 20th in men's sabre ... The appearance in the competition, held in San Antonio, Texas, was the first of his career ... Finished 10th at NCAA Regionals in 2011, 2012 and 2013"," Born June 10, 1992, in Dix Hills, N.Y. ... Son of Jeffrey and Ellie Austin ... Fun facts are that he played trombone in high school and loves to sing in the shower",27],
    ["Graduated from Walnut Hills High School ... Participated in fencing for four years and lettered three years ... Became involved with fencing due to the Olympian Ed Wright. Working toward a double major in journalism and philosophy ... Member of AEPi Fraternity ","Qualified for 2013 NCAA Regionals and placed 28th in men's foil","Born Sept. 1, 1994, in Cincinnati, Ohio ... Son of Kerry and Bonnie Burte ... Has one sister ... Favorite pastimes are reading, traveling and long walks on the beach ... Favorite sport other than fencing is soccer ... A fun fact is he can fall asleep anywhere ... The athlete he most admires is Pheidippides ... After graduation, he plans to travel ... His dream job is to be President of the United States or a National Geographic photojournalist ... A little-known talent is that he is very lucky",28],
    ["Graduate of Westborough (Mass.) High School ... Fenced for Boston Fencing Club for eight years prior to coming to UNC ... Picked up the sport after seeing it at Boy Scout camp, and the fenced for a year at Portland Fencing Center before moving to Boston. Majoring in computer science","Is in his first season on the squad","Born May 19,1995, in Cleveland, Ohio ... Son of Lee Ann Desai ... His mother played field hockey and lacrosse at Colby-Sawyer College ... Has one sister ... Favorite pastimes are playing video games, hanging out with friends, programming and skiing ... Favorite sports other than fencing are lacrosse and  skiing ... Athletes he most admires are Ed Ballinger and Charles 'Buzz' Bowers ... After graduation, hopes to have the opportunity to explore and live in different countries ... Little known talent is that he's a hobbyist engineer and 3D-printer technician",29],
    ["Graduated from North Surry High School and participated in track and field for one year ... Played soccer for three years and was named Defensive Player of the Year","In his second season on the fencing team","Born May 6, 1994, in Mount Airy, N.C.  ... Has one sister ... Favorite sport other than fencing is volleyball",30],
    ["At Palmerton (Pa.) High School, captained her high school team and was honored as MVP and Most Aggressive Player ... Also lettered four years in track ... As a junior was league champion in the 100, 400 and triple jump, and district champion in the 100, 200 and 400 ... Top Female Athlete her junior and senior years ... President of National Honor Society ","Did not see action and will count 2013 as a redshirt season, retaining four years of eligibility"," Born in Allentown, Pa. ... Daughter of Gerald and Cynthia Pereira ... Favorite pastimes are playing Call of Duty, doing puzzles, cooking, playing with her kitten, and hanging out with her family ... Favorite sports other than field hockey are football and ice hockey (to watch) ... Favorite food is all types of vegetables ... Fun fact is that she was a cheerleader for eight years until her school started offering field hockey and she quit cheerleading to play ... Athlete she most admires is teammate Abby Frey because 'she can play any sport she wants and she amazing at it. Also, she is an outstanding athlete in general, she's in great shape, and can accomplish anything she puts her mind to' ... After graduation, plans to continue her education by studying biomedical engineering in graduate school ... Dream job is to be a model, but also would like to do something with her degree",31],
    ["Born in Raleigh ... Daughter of Jan and Tommy Shealy ... Has one younger sister ... Her father played baseball at UNC and her grandfather played baseball at Georgia ... Lived in London for three years ... Made a hole-in-one when she was 10 ... Plays the cello ... Has climbed Mt. Shasta in northern California"," For the second year in a row, honored as the NCAA Elite 89 Award winner as the player at the field hockey final four with the highest cumulative GPA ... Honored as the ACC Field Hockey Scholar-Athlete of the Year and also named to the All-ACC Academic Team ... Second-team Capital One Academic All-America selection as part of the At-Large team","At Charlotte Country Day School, lettered four years in field hockey and basketball and three in track ... As a senior in 2010, was named NFHCA All-America and All-South Region ... Two-time all-state selection and three-time all-conference pick ... Team MVP and Charlotte Field Hockey Player of the Year in her junior and senior years ... Helped her team to a state championship in 2009 ... Named to the 2010-11 NFHCA National Academic Squad ... NSCA Strength and Conditioning All-America pick in 2011 ... Her school's Scholar Athlete of the Year for 2010-11 ... Served as president of Honor Council and was a Joe Martin Bank of America Scholar",32],
    ["Born in Waterville, Maine ... Daughter of Amy and Brian Bernatchez ... Her mother played field hockey at the University of Maine, and her sister, Katie, is a junior field hockey player at Boston University ... Favorite pastimes are playing sports, boating and wakeboarding ... Favorite sport other than field hockey is basketball ... Fun fact is that she was a gymnast for eight years ... Athlete she most admires is Michael Jordan ... After college, hopes to play field hockey internationally ... Dream job is working for a professional sports team","Named to the ACC Academic Honor Roll. Member of the U.S. Under-21 National Team","At Messalonskee High School in Oakland, Maine, named Miss Maine Field Hockey and Kennebec Journal Player of the Year as a senior ... Four-time all-state and all-conference honoree ... Two-year team MVP ... Team captain as a senior ... Scored 47 goals in her senior season, setting a new state scoring record ... Her team was Eastern Maine runner-up four years in a row ... MVP of the 2013 Senior All-Star Game ... Also played three years of varsity lacrosse, earning all-conference honors as a senior when her team won the conference title ... Named the Top Female Athlete in her senior class ... Earned High Honors with Distinction all four years",33],
    ["Born in Harare, Zimbabwe ...Daughter of John and Judy Travers ... Has four older siblings ... Favorite pastime is waterskiing ... Favorite pregame meal is watermelon .... Favorite sport to play besides field hockey is squash ... Also loves playing cricket ... After college, hopes to work in the field of sports psychology ... Dream job is to host a travel show ... Highlight of her athletic career has been playing for the U21 Zimbabwe team ... Her sister Tara has had the biggest impact on her field hockey development ... Fun fact is that she and her family are featured in an Animal Planet show called, 'There's a Rhino in My House.'","Named to the All-ACC Academic Team ... Scored seven goals (tied for fourth on the team) and added one assist ... Anchored the Tar Heel back line ... Recipient of the team's Carmen and Michael Hooker Leadership Award","Attended Peterhouse Girls School ... Member of the U21, U18 and U16 teams for Zimbabwe ... Also played two years of golf, representing Zimbabwe ... Member of the U16 and U18 tennis teams for Zimbabwe ... Singles and doubles champion 2004-09 ... Member of Zimbabwe's U18 and U16 squash teams ... Also in the debate club",34],
    ["Born in Wolverhampton, England ... Daughter of Alan Craddock ... Favorite pastimes are going to movies and watching football (supporting the Carolina Panthers to the Super Bowl!) ... Favorite sport besides field hockey is football ... Favorite foods are Grandma Mimi's crackers and Mrs. Plyler's trail mix ... Fun fact is that she loves country music ... Athlete she most admires is Cam Newton ... Dream job is to work with a football team ","Appeared in 18 games (missed six due to injury) and started 14 of those ... Scored 13 goals and added five assists for 31 points, third on the team ... A team-high five of her goals were game winners ... Named to the All-ACC Academic Team","Graduated from Repton School in Derbyshire, England ... Attended University of Bristol and played for the University of Bristol Ladies Hockey Club",35],
    ["Parents are Rick and Maryann Bateman ... born May 14, 1994.","2nd in NCISAA 3A State Championship ... NCISAA All State","Four-year golfer at Providence Day School, Charlotte, N.C. ... member of National Honor Society ... president of Film and Media club for two years ... member of Beta Club ... member of Key Club ... member of Headmaster's and Dean's list.",36],

    ["Son of Jim and Nancy Daly...has two younger sisters who both play tennis ... full name is Connor Michael Daly...born in Thousand Oaks, Calif., in December 1993...business administration major.","Played in singles and doubles at the ITA Carolinas Regional...one of two players on the team who won the 2014 ITA Scholar-Athlete Award...named to 2013-14 ACC Academic Honor Roll...earned spot on the Dean's List both semesters of his sophomore year.","Was one of the Top 30 tennis players in Southern California in the 16s and 18s ... played #2 singles at Oaks Christian High School as a freshman and sophomore ... named All-Tri Valley League his freshman and sophomore campaigns ... member of Dean's List all throughout high school.",42],
    ["Full name is Charles Stuart DePaolo...son of Chuck and Sally DePaolo...born in December 1993 in Asheville... was the first chair piccolo in the Asheville Youth Orchestra and Wind Symphony as a freshman and sophomore ... his mother, Sally, played tennis at Florida State ... his brother, Jack, played for Georgia Tech and Claremont McKenna College...majoring in economics...his father played football at Sewanee (University of the South)....sister played basketball at Johns Hopkins.","Was 3-6 in singles play and 3-4 in doubles play in the fall of his sophomore year...split four three-set singles matches in the fall.","Attended Asheville High School...one of the top-ranked players in the nation all through his junior tennis career ... ranked 49th nationally as a senior and 62nd as a junior ... was ranked in the Top 150 as a sophomore and the Top 175 as a freshman ... USTA state champion his freshman year...member of high school state championship team ... played #1 singles position on the team ... 2010 Class 3A Western North Carolina Player of the Year.",43],
    ["Full name is Øystein Steiro, Jr. ...parents are Øystein Steiro, Sr. and Berit Bergsjø ... economics major ... has a sister who reached as high as 499th in WTA rankings at age 18...stands 6-6 and plays with his right hand...active in Carolina Leadership Academy program where he was a member of the Rising Stars program in 2012-13.","Won the Norwegian championship last summer heading into his junior year...heads into spring season ranked 50th nationally in ITA doubles ranking with partner Nelson Vick...went 9-4 in singles and 8-2 in doubles during the fall campaign...played five three-set matches...played all 10 fall doubles matches with Nelson Vick, going 8-2...reached the finals of the ITA Carolinas Regional in doubles with Nelson Vick...was 4-0 in ITA All-American Championships pre-qualifying tournament in Tulsa, meriting a spot in the qualifying phase of the tournament...took third place in the Black singles draw at the Duke Fab Four Invite...paired with Nelson Vick to capture the Blue flight doubles crown at the Duke Fab Four Invite.","Held prep ranking of No. 1 in Norway in the 14s, 16s, and 18s ... ranked No. 33 in Europe in the 16s ... won Norwegian Championship for 16s in 2008 and for 18s in 2009 in addition to capturingone ITF singles title and two ITF doubles titles, both in Oslo ... member of Norwegian Davis Cup team ... played bandy, a Scandinavian ice skating sport, in high school as a midfielder ... was member of the top bandy team in the country ... nominee for top athlete in his high school.",44],
    ["Heads intro the spring season of his freshman year ranked 17th nationally in the ITA singles rankings...one of the most highly recruited members of the high school class of 2013...full name is Ronald Ray Schneider...plans to major in business administration...son of Ron and Anita Schneider...born in September 1994 in Bloomington, Ind. ...both of his parents attended the University of Evansville where his father played tennis and his mother was a diver.","Had a tremendous fall tournament season as a freshman...went 12-2 overall in singles and 4-2 in doubles...played one-half of his singles matches against nationally-ranked players, going 5-2...went 3-2 in three-set matches...reached the Round of 16 in singles at the ITA Carolinas Regional...advanced to the doubles quarterfinals in the same tournament while playing with Brett Clark...started the fall season by winning his first nine singles matches...reached the Round of 16 at the ITA All-American Championships in Tulsa...he went 3-0 in the qualifying phase of the tournament and then won two of three matches in the main draw...in his first tournament as a Tar Heel he won the singles championship at the UVA Ranked Plus One tournament.","2013 alumnus of Bloomington High School South...2013 USTA Boys 18s national doubles champion with Paul Oosterbaan...with that win the duo earned a wild card into the main draw of the 2013 U.S. Open doubles tournament...it was Schneider's third title at Kalamazoo in his career...he won the USTA National Open in Lexington, Ky., in July 2013 over his Tar Heel freshman teammate Jack Murray...on June 25, 2013, he finished off a great week to win the Midwest Sectional qualifier in the U.S. Open National Playoffs...went 6-0 in the tournament without dropping a set...beat Kevin Metka of Ohio State 6-1, 6-4 in the tournament final...in 2011 at USTA Nationals in Kalamazoo he won both the singles and doubles in the Boys 16s...U.S. Open Juniors participant in both singles and doubles in 2011 and 2012...three-time individual Indiana state champion (2010, 2011, 2012)...his team finished second in the state championship in 2009...had a 99-1 record at #1 singles during his high school career...ranked #1 nationally on TennisRecruiting.net for the Class of 2013 from 2011-13...member of National Honor Society...executive chair of Bloomington South's Dance Marathon...academic honor roll all four years with a GPA of 4.0 or above.",45],
    ["Frank Joseph Abbondanza is the son of Ron and Carol Abbondanza • Born March 1, 1993 in Mount Sinai, N.Y. ","Started all 15 duals wrestling at 174 and 197 • Finished 8-21 overall and 2-13 in duals • Took third place at the Wolfpack Open at 174 pounds • Dual wins came against South Dakota State and NC State • Defeated NC State's Josh Lackey by major decision.","Attended Mount Sinai High School • 2011 New York State Finalist at 189 • Named First Team All-Long Island • Earned all-section honors two times • A four-time all-league selection • Posted a 71-7 record in his final two years • Captained the team his final two seasons • Named the Suffolk County Academic Wrestler of the Year as a senior • Graduated third in his class • Member of the National Honor Society • Also played football.",46],
    ["Christian Barber is the son of Jeffrey and Vanessa Barber • Born Sept. 27, 1992 in Westfield, N.J. ","Compiled a 22-14 record at 149 pounds, including a 7-4 mark in duals • Finished second at the Wolfpack Open and sixth at the Nittany Lion Open • Scored a pair of wins in ACC action over opponents from Maryland and NC State, including a major decision over NC State's Tomas Gantt • Collected pins against Clarion's Zachary Ross and Indiana's Preston Keiffer.","Attended Westfield High School • Captured the 2011 New Jersey State Title • Posted a 41-1 record as a senior • Two-time team captain • Turned in a 112-21 record during his four-year career • Honor roll student.",47],
    ["Howell Houston Clements is the son of Dean and Holly Clements • Born March 18, 1994, in Chattanooga • Grandfather Howell Gilbert Clements wrestled at Vanderbilt and was an SEC runner-up.","Finished 11-9 on the year at 149 pounds with three pins and two major decisions • Won three times at both the Hokie Open and the East Stroudsburg Open.","Attended The Baylor School in Chattanooga, Tenn. • Five year varsity starter, starting at 135 pounds and finishing at 182 • Two-time NHSCA All-American • Ohio Tournament of Champions champion • Four-time state placer and team captain as a senior • Three-time Chattanooga Best of Preps All-Star selection • Compiled a record of 129-24 in his prep career • Also played running back and nose guard for the football team, playing in back-to-back state championship games • Very active prep who was a four-year honor roll student and National Honor Society member.",48],
    ["Evan Richard Henderson is the son of Allen and Lydia Henderson • Born Sept. 7, 1992 in Johnstown, Pa. • Twin brother, Robert, is also a member of the UNC wrestling team.","Finished sixth at the NCAA Championships at 141 to earn All-America honors, the first Tar Heel to do so since Evan Sola in 2005 • Also won the ACC title at 141 with a 10-2 win over No. 12 Zach Neibert of Virginia Tech • Compiled a 37-9 record on the year, including a 13-1 mark in duals • His 37 wins place him seventh in school history for single-season victories • Had 11 pins on the year, including a fastest of 1:11 • Also had seven major decision wins and three by technical fall • Won the Wolfpack Open at 151 • Also took second at the Nittany Lion Open, third at the Hokie Open and sixth at the Midlands Championships.","NCAA Participant • Starter at 141 pounds • Posted a 27-11 overall record with a 15-5 dual record • Won his first 10 bouts as a Tar Heel • Placed first at the Hokie Open after going 5-0 with two pins and a major decision • Went 4-0 at Wrestle for a Cure with all victories coming from pins • Earned seventh place at the Cliff Keen Invitational by going 5-2 with two pins and a major decision • Claimed wins over ranked foes Nathan Pennesi (West Virginia) and Mike Nevinger (Cornell) at Cliff Keen • Collected three major decisions, one technical fall, and ten pins in the season • His ten pins were the most for any Tar Heel in 2011-12 • Also had the fastest pin in 0:35. ",49],
    ["Jacob Reid Crawford is the son of John Crawford and Tammy Ferrari • Born May 2, 1994 in Pittsburgh, Pa.","Finished 10-6 on the year wrestling at 157 pounds • Won three times by pin and twice by major decision • Took third at the Franklin & Marshall Open • Defeated Drexel's Austin Sommer for his first career dual win.","Junior National Champion • Three-time Virginia State Champion • Ranked 12th in the nation • Super 32 Champion • Placed second and fourth in the Beast of the East Tournament • Posted a 45-3 record his senior year and 47-2 his junior year • Finished with an overall record of 200-8 • Honor Roll student.",50]
]


players.each do |player|
  Player.create(player_name: player[0],
                player_year:player[1],
                player_hometown:player[2],
                player_pic:player[3],
                team_id:player[4]  )
end

teams.each do |team|
  Team.create(
      team_name:team[0],
      gender:team[1],
      coach:team[2],
      assistant_coach:team[3],
      team_pic:team[4]
  )
end
bios.each do |bio|
  Bio.create(
            personal_info: bio[0],
            current_year: bio[1],
            more_info: bio[2],
            player_id: bio[3]
  )

end
